"""empty message

Revision ID: 435963f4aebe
Revises: 97ee5b60a515
Create Date: 2017-07-30 15:38:16.995925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '435963f4aebe'
down_revision = '97ee5b60a515'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('country', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'country')
    # ### end Alembic commands ###
