"""empty message

Revision ID: 480ba3db66a7
Revises: e31a5c516ac1
Create Date: 2017-06-14 21:35:17.818102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '480ba3db66a7'
down_revision = 'e31a5c516ac1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=32), nullable=False),
    sa.Column('current_owner', sa.String(length=20), nullable=True),
    sa.Column('stock_amount', sa.Integer(), nullable=True),
    sa.Column('stock_price', sa.Integer(), nullable=True),
    sa.Column('market_cap', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=32), nullable=False),
    sa.Column('owner', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_stock_relationship_table',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'stock_id')
    )
    op.add_column(u'users', sa.Column('current_balance', sa.Integer(), nullable=False))
    op.add_column(u'users', sa.Column('current_net_worth', sa.Integer(), nullable=False))
    op.add_column(u'users', sa.Column('user_type', sa.Integer(), nullable=False))
    op.add_column(u'users', sa.Column('username', sa.String(length=20), nullable=False))
    op.drop_column(u'users', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'users', sa.Column('name', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.drop_column(u'users', 'username')
    op.drop_column(u'users', 'user_type')
    op.drop_column(u'users', 'current_net_worth')
    op.drop_column(u'users', 'current_balance')
    op.drop_table('user_stock_relationship_table')
    op.drop_table('stocks')
    op.drop_table('companies')
    # ### end Alembic commands ###
