"""empty message

Revision ID: 97ee5b60a515
Revises: 480ba3db66a7
Create Date: 2017-06-14 21:54:13.438541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97ee5b60a515'
down_revision = '480ba3db66a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stocks', 'owner')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stocks', sa.Column('owner', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
